import { CheckCircle2, ClipboardPlus, Pencil, Send, Trash2, XCircle } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { PageHeader } from '../components/ui/PageHeader'
import { Button } from '../components/ui/Button'
import { Card, CardBody, CardHeader } from '../components/ui/Card'
import { Modal } from '../components/ui/Modal'
import { Badge } from '../components/ui/Badge'
import { EmptyState, ErrorState, LoadingState } from '../components/ui/States'
import { cancelPresenterSubmission, createPresenterSubmission, getPresenterPortalLives, getPresenterPortalOptions, resubmitPresenterSubmission, updatePresenterSubmission, type PresenterPortalOptions, type PresenterSubmission, type PresenterSubmissionPayload } from '../services/presenter-portal'
import { QK } from '../services/query-keys'
import { useCurrentUser } from '../stores/auth-store'
import { extractErrorMessage } from '../services/api'
import { formatDate, formatMoney } from '../utils/format'
import { currentMonth, isoFromLocalDateTime, localDateTimeValue, submissionStatusLabel, submissionStatusTone } from '../utils/presenter-portal'
import { useToast } from '../components/ui/Toast'

type FormState = { marcaId: string; cabineId: string; marcaDescricao: string; inicio: string; fim: string; observacao: string; gmv: string; pedidos: string }
const blankForm = (): FormState => ({ marcaId: '', cabineId: '', marcaDescricao: '', inicio: '', fim: '', observacao: '', gmv: '', pedidos: '' })

function formFromSubmission(item?: PresenterSubmission): FormState {
  if (!item) return blankForm()
  return { ...blankForm(), marcaId: item.marca_id ?? '', cabineId: item.cabine_id ?? '', marcaDescricao: item.marca_nome ?? item.marca_descricao ?? '', inicio: localDateTimeValue(item.iniciado_em), fim: localDateTimeValue(item.encerrado_em), observacao: item.observacao ?? '', gmv: item.gmv_declarado?.toString() ?? '', pedidos: item.pedidos_declarados?.toString() ?? '' }
}

function payloadFromForm(form: FormState): PresenterSubmissionPayload | null {
  const gmv = form.gmv.trim() === '' ? undefined : Number(form.gmv.replace(',', '.'))
  const pedidos = form.pedidos.trim() === '' ? undefined : Number(form.pedidos)
  if ((!form.marcaId && !form.marcaDescricao.trim()) || !form.inicio || !form.fim || (gmv !== undefined && (!Number.isFinite(gmv) || gmv < 0)) || (pedidos !== undefined && (!Number.isInteger(pedidos) || pedidos < 0))) return null
  const inicio = isoFromLocalDateTime(form.inicio); const fim = isoFromLocalDateTime(form.fim)
  if (!inicio || !fim || new Date(fim) <= new Date(inicio)) return null
  return { marca_id: form.marcaId || undefined, marca_descricao: form.marcaId ? undefined : form.marcaDescricao.trim(), cabine_id: form.cabineId || undefined, iniciado_em: inicio, encerrado_em: fim, observacao: form.observacao.trim() || undefined, gmv_declarado: gmv, pedidos_declarados: pedidos }
}

function SubmissionModal({ item, options, errorMessage, onClose, onSave, busy }: { item: PresenterSubmission | null; options?: PresenterPortalOptions; errorMessage?: string; onClose: () => void; onSave: (payload: PresenterSubmissionPayload) => void; busy: boolean }) {
  const [form, setForm] = useState(() => formFromSubmission(item ?? undefined)); const [error, setError] = useState(errorMessage ?? '')
  useEffect(() => { if (errorMessage) setError(errorMessage) }, [errorMessage])
  const requestId = useRef(typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`)
  const set = (key: keyof FormState, value: string) => setForm((old) => ({ ...old, [key]: value }))
  return <Modal open title={item ? 'Corrigir envio' : 'Registrar live concluída'} subtitle={item ? 'Salve as alterações e depois reenvie para revisão.' : 'O envio ficará em revisão antes de entrar no seu desempenho.'} onClose={onClose} closeDisabled={busy} footer={<div className="flex w-full justify-end gap-2"><Button variant="secondary" onClick={onClose} disabled={busy}>Cancelar</Button><Button icon={Send} isLoading={busy} onClick={() => { const payload = payloadFromForm(form); if (!payload) { setError('Preencha a marca, horários válidos e métricas não negativas.'); return }; onSave({ ...payload, request_id: item ? undefined : requestId.current }) }}>{item ? 'Salvar correção' : 'Enviar para revisão'}</Button></div>}>
    <div className="grid gap-4 p-1">{options?.marcas.length ? <label className="grid gap-1.5 text-sm font-semibold text-ink">Marca<select className="design-input h-11 px-3" value={form.marcaId} onChange={(e) => set('marcaId', e.target.value)} required><option value="">Selecione a marca</option>{options.marcas.map((marca) => <option key={marca.id} value={marca.id}>{marca.nome}</option>)}</select></label> : <label className="grid gap-1.5 text-sm font-semibold text-ink">Marca<input className="design-input h-11 px-3" value={form.marcaDescricao} onChange={(e) => set('marcaDescricao', e.target.value)} maxLength={200} required /></label>}{options?.cabines.length ? <label className="grid gap-1.5 text-sm font-semibold text-ink">Cabine<select className="design-input h-11 px-3" value={form.cabineId} onChange={(e) => set('cabineId', e.target.value)}><option value="">Não informada</option>{options.cabines.map((cabine) => <option key={cabine.id} value={cabine.id}>{cabine.nome || `Cabine ${cabine.numero ?? ''}`}</option>)}</select></label> : null}<div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold text-ink">Início<input className="design-input h-11 px-3" type="datetime-local" value={form.inicio} onChange={(e) => set('inicio', e.target.value)} required /></label><label className="grid gap-1.5 text-sm font-semibold text-ink">Fim<input className="design-input h-11 px-3" type="datetime-local" value={form.fim} onChange={(e) => set('fim', e.target.value)} required /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold text-ink">GMV declarado <span className="font-normal text-ink-muted">(opcional)</span><input className="design-input h-11 px-3" inputMode="decimal" value={form.gmv} onChange={(e) => set('gmv', e.target.value)} /></label><label className="grid gap-1.5 text-sm font-semibold text-ink">Pedidos declarados <span className="font-normal text-ink-muted">(opcional)</span><input className="design-input h-11 px-3" inputMode="numeric" value={form.pedidos} onChange={(e) => set('pedidos', e.target.value)} /></label></div><label className="grid gap-1.5 text-sm font-semibold text-ink">Observação <span className="font-normal text-ink-muted">(opcional)</span><textarea className="design-input min-h-24 p-3" value={form.observacao} onChange={(e) => set('observacao', e.target.value)} maxLength={2000} /></label>{error ? <p role="alert" className="text-sm text-[var(--danger)]">{error}</p> : null}</div>
  </Modal>
}

export function PresenterPortalLivesPage() {
  const user = useCurrentUser(); const client = useQueryClient(); const toast = useToast(); const [mes, setMes] = useState(currentMonth); const [editing, setEditing] = useState<PresenterSubmission | null | undefined>(undefined); const [cancelling, setCancelling] = useState<PresenterSubmission | null>(null)
  const query = useQuery({ queryKey: QK.presenterPortalLives(user?.tenant_id ?? '', user?.id ?? '', mes), queryFn: () => getPresenterPortalLives(mes), enabled: Boolean(user?.id && user?.tenant_id) })
  const options = useQuery({ queryKey: ['presenter-portal-options', user?.tenant_id ?? '', user?.id ?? ''], queryFn: getPresenterPortalOptions, enabled: Boolean(user?.id && user?.tenant_id && editing !== undefined) })
  const invalidate = () => client.invalidateQueries({ queryKey: QK.presenterPortalLives(user?.tenant_id ?? '', user?.id ?? '', mes) })
  const save = useMutation({ mutationFn: ({ item, payload }: { item?: PresenterSubmission | null; payload: PresenterSubmissionPayload }) => item ? updatePresenterSubmission(item.id, payload) : createPresenterSubmission(payload), onSuccess: (_data, variables) => { void invalidate(); setEditing(undefined); toast.push(variables.item ? 'Correção salva. Reenvie quando estiver pronta.' : 'Live enviada para revisão.', 'success') }, onError: (error) => toast.push(extractErrorMessage(error), 'error') })
  const resend = useMutation({ mutationFn: resubmitPresenterSubmission, onSuccess: () => { void invalidate(); toast.push('Envio reenviado para revisão.', 'success') }, onError: (error) => toast.push(extractErrorMessage(error), 'error') })
  const cancel = useMutation({ mutationFn: cancelPresenterSubmission, onSuccess: () => { void invalidate(); setCancelling(null); toast.push('Envio cancelado.', 'success') }, onError: (error) => toast.push(extractErrorMessage(error), 'error') })
  if (query.isLoading) return <LoadingState label="Carregando suas lives" />
  if (query.isError || !query.data) return <ErrorState message={extractErrorMessage(query.error)} onRetry={() => void query.refetch()} />
  return <div className="space-y-6"><PageHeader title="Minhas lives" subtitle="Registre apenas lives já concluídas. Cada envio precisa de revisão antes de contar nas métricas." actions={<><label className="grid gap-1 text-xs font-semibold text-ink-muted">Mês<input aria-label="Mês das minhas lives" className="design-input h-10 px-3 text-sm" type="month" value={mes} onChange={(e) => setMes(e.target.value)} /></label><Button icon={ClipboardPlus} onClick={() => setEditing(null)}>Registrar live</Button></>} />
    <Card><CardHeader><h2 className="text-lg font-bold text-ink">Lives concluídas</h2><p className="mt-1 text-sm text-ink-muted">Histórico oficial que já compõe o seu desempenho.</p></CardHeader><CardBody className="p-0">{query.data.items.length === 0 ? <EmptyState title="Nenhuma live concluída no período" /> : query.data.items.map((item) => <div key={item.id} className="grid gap-2 border-b border-line px-5 py-4 last:border-b-0 sm:grid-cols-[1fr_auto_auto]"><div><p className="font-semibold text-ink">{item.marca_nome ?? 'Marca não informada'}</p><p className="mt-1 text-sm text-ink-muted">{formatDate(item.iniciado_em)} · {item.cabine_nome ?? 'Cabine não informada'}</p></div><p className="num text-sm font-bold text-ink">{formatMoney(item.gmv, true)}</p><p className="text-sm text-ink-muted">{item.horas.toLocaleString('pt-BR', { maximumFractionDigits: 1 })}h · {item.pedidos} pedidos</p></div>)}</CardBody></Card>
    <Card><CardHeader><h2 className="text-lg font-bold text-ink">Meus envios</h2><p className="mt-1 text-sm text-ink-muted">Acompanhe a revisão e corrija somente envios devolvidos.</p></CardHeader><CardBody className="p-0">{query.data.submissoes.length === 0 ? <EmptyState title="Nenhum envio no período" description="Registre uma live concluída para iniciar a revisão." /> : query.data.submissoes.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 border-b border-line px-5 py-4 last:border-b-0"><div className="min-w-[180px] flex-1"><p className="font-semibold text-ink">{item.marca_nome ?? item.marca_descricao ?? 'Marca informada no envio'}</p><p className="mt-1 text-sm text-ink-muted">{formatDate(item.iniciado_em)}{item.motivo_devolucao ? ` · ${item.motivo_devolucao}` : ''}</p></div><Badge tone={submissionStatusTone(item.status)}>{submissionStatusLabel(item.status)}</Badge>{item.status === 'devolvida' ? <><Button variant="secondary" icon={Pencil} onClick={() => setEditing(item)}>Corrigir</Button><Button icon={Send} isLoading={resend.isPending} onClick={() => resend.mutate(item.id)}>Reenviar</Button><Button variant="ghost" icon={Trash2} onClick={() => setCancelling(item)}>Cancelar envio</Button></> : null}{item.status === 'aprovada' ? <CheckCircle2 className="h-5 w-5 text-[var(--success)]" aria-label="Aprovada" /> : null}{item.status === 'cancelada' ? <XCircle className="h-5 w-5 text-ink-muted" aria-label="Cancelada" /> : null}</div>)}</CardBody></Card>
    {editing !== undefined ? <SubmissionModal item={editing} options={options.data} errorMessage={save.error ? ((save.error as { response?: { data?: { error?: string } } }).response?.data?.error ?? extractErrorMessage(save.error)) : undefined} busy={save.isPending} onClose={() => setEditing(undefined)} onSave={(payload) => save.mutate({ item: editing, payload })} /> : null}
    <Modal open={Boolean(cancelling)} title="Cancelar envio" subtitle="Este envio será cancelado e não poderá mais ser editado ou reenviado." onClose={() => setCancelling(null)} closeDisabled={cancel.isPending} footer={<div className="flex w-full justify-end gap-2"><Button variant="secondary" disabled={cancel.isPending} onClick={() => setCancelling(null)}>Voltar</Button><Button variant="danger" isLoading={cancel.isPending} onClick={() => { if (cancelling) cancel.mutate(cancelling.id) }}>Cancelar envio</Button></div>}>{cancel.isError ? <p role="alert" className="text-sm text-[var(--danger)]">{extractErrorMessage(cancel.error)}</p> : <p className="text-sm text-ink-muted">Use esta ação apenas quando não pretende corrigir o envio devolvido.</p>}</Modal>
  </div>
}
export default PresenterPortalLivesPage
